---
name: Secret scan

on:
  push:
    branches: [main, "feat/**", "fix/**", "chore/**", "release/**"]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

jobs:
  call:
    uses: chrysa/github-actions/.github/workflows/secret-scan.yml@v1.4.4